### ISSUE TITLE
importing issues

### ISSUE THREAD

**Issue by parthp08** [AlexS12/FlightMechanics.jl#36]
hi Alex, i changed src/aircrafts module here https://github.com/parthp08/FlightMechanics.jl/tree/master/src/aircrafts.
what do you think about this way. it passed all tests locally and on travis cl.

**Comment by parthp08** [comment]
as you pointed out this way it is easy to import other module regardless of which file imported first as long as imports.jl is imported before them.

**Comment by AlexS12** [comment]
I agree with that direction, but what do you thin about joining everything under `F16` and `C310` in two single files? Then, constants, methods, structs related to one aircraft would be together as they are, once included in `Aircraft.jl`

Hence, for me, it would make sense to add the imports directly in `Aircrafts.jl`  instead of adding extra source files. I think that at these point of the project, condensing everything in less source files will be useful and we will always have time to separate things if needed.

**Comment by parthp08** [comment]
It would be easy to add new stuff or change with saperate files.
But as both aircrafts model is nearly complete i agree that we should join everything under one files.

**Comment by parthp08** [comment]
And about linearization, should I just use flat earth model or you would like to add them as a function arguments to choose from.

**Comment by AlexS12** [comment]
I agree that separate files should be easier at some point. But as I see now, most julia packages tend to group everything under big files. There is no modularization like in python... and, moreover, some parameters and methods are shared between our distinct files for each aircraft.

**Comment by AlexS12** [comment]
> And about linearization, should I just use flat earth model or you would like to add them as a function arguments to choose from.

We can open a different issue for this one. I would say that it would be nice if the model and the aircraft could be parameters of the linearization function. But we need to establish some common interfaces. Does it make sense to you?
